title: "Kevin Patrascu Portfolio"
description: "Built by using Markdown and GitHub Actions"
baseurl: "" 
url: "https://bloofie.github.io"
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag