name: Build and Deploy

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler & Jekyll
        run: |
          gem install bundler
          gem install jekyll bundle

      - name: Bundle Init
        run: bundle init

      - name: Bundle Install
        run: bundle install

      - name: Install & Build Jekyll Site
        run: bundle exec jekyll serve

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site